/**
 * Migration 0008 — creates evidence_reports.
 *
 * Persisted compliance evidence reports — one row per (tenantId, periodStart,
 * periodEnd). Generated by the monthly cron (AWO-81) or on-demand from the
 * compliance route. Stores both the rendered PDF (as base64 TEXT, fine for
 * the < 1 MB monthly artifact size) and the JSON snapshot of the underlying
 * aggregations so the admin UI can show summary cards without re-rendering.
 *
 * The unique (tenant_id, period_start, period_end) constraint dedupes —
 * a re-run of the cron for the same window updates timestamps but does not
 * insert a second row.
 *
 * Forward-only, idempotent via __drizzle_migrations.
 */

import type { Database } from "better-sqlite3";

export function migrate(sqlite: Database): void {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL UNIQUE,
      created_at INTEGER NOT NULL DEFAULT (unixepoch())
    );
  `);

  const existing = sqlite
    .prepare("SELECT 1 FROM __drizzle_migrations WHERE hash = ?")
    .get("v8-evidence-reports");
  if (existing) return;

  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS evidence_reports (
      id TEXT PRIMARY KEY,
      tenant_id TEXT NOT NULL,
      report_id TEXT NOT NULL,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      generated_at TEXT NOT NULL,
      engine_name TEXT NOT NULL,
      html_size INTEGER NOT NULL DEFAULT 0,
      pdf_byte_length INTEGER NOT NULL DEFAULT 0,
      pdf_base64 TEXT,
      summary_json TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'complete',
      error TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE (tenant_id, period_start, period_end)
    );
    CREATE INDEX IF NOT EXISTS idx_evidence_reports_tenant
      ON evidence_reports(tenant_id);
    CREATE INDEX IF NOT EXISTS idx_evidence_reports_period
      ON evidence_reports(tenant_id, period_start);
  `);

  sqlite
    .prepare("INSERT INTO __drizzle_migrations (hash) VALUES (?)")
    .run("v8-evidence-reports");
}
