/**
 * Evidence-report service — aggregates policy_decisions + scanner_findings
 * for a tenant + period, renders to HTML via the template, renders the HTML
 * to a PDF via the configured PdfEngine, and persists the result.
 *
 * The cron in evidence-report-cron.ts wraps this; routes can also call it
 * on-demand for ad-hoc reports.
 */

import { createHash, randomUUID } from "node:crypto";
import { and, eq, gte, lt, sql, desc } from "drizzle-orm";
import { join } from "node:path";
import type { PdfEngine } from "@agentworks/pdf";
import { getDb } from "../db/index.js";
import {
  policyDecisions,
  scannerFindings,
  evidenceReports,
  tenants,
} from "../db/schema.js";
import {
  renderEvidenceReportHtml,
  type EvidenceReportData,
  type ViolationCategory,
  type FindingsCategory,
  type FindingHighlight,
  type DecisionSummary,
} from "../templates/evidence-report.js";
import { signPdf } from "./evidence-report-signing.js";

/** Relative path under the data directory where HMAC signing keys are stored. */
const KEY_DIR = "keys";

export interface GenerateOptions {
  tenantId: string;
  periodStart: string;
  periodEnd: string;
  engine: PdfEngine;
  /** Directory for data/keys/. Default: ./data/keys */
  keyDir?: string;
  /** Override for tests. Default: new Date().toISOString(). */
  now?: () => string;
}

export interface GenerateResult {
  id: string;
  reportId: string;
  tenantId: string;
  periodStart: string;
  periodEnd: string;
  generatedAt: string;
  engineName: string;
  pdfByteLength: number;
  pdfBase64: string;
  htmlSize: number;
  status: "complete";
  summary: EvidenceReportData;
  /** SHA-256 of the raw (pre-trailer) PDF bytes. */
  pdfHash: string;
  /** HMAC-SHA256 over the signature metadata. */
  hmac: string;
  /** ISO timestamp of signing. */
  signedAt: string;
}

export async function generateEvidenceReport(
  opts: GenerateOptions,
): Promise<GenerateResult> {
  if (opts.periodStart >= opts.periodEnd) {
    throw new Error(
      `periodStart ${opts.periodStart} must be before periodEnd ${opts.periodEnd}`,
    );
  }
  const now = (opts.now ?? (() => new Date().toISOString()))();
  const data = aggregateEvidenceReportData({
    tenantId: opts.tenantId,
    periodStart: opts.periodStart,
    periodEnd: opts.periodEnd,
    generatedAt: now,
  });
  const html = renderEvidenceReportHtml(data, data.findingsHighlights.length);
  const rendered = await opts.engine.render(html);

  // Deterministic id derived from tenant + period so every concurrent caller
  // arrives at the same id. SQLite UNIQUE constraint on (tenant_id, period_start,
  // period_end) dedupes — the first writer inserts, rest hit onConflict and update.
  // Using only tenant+period (not now) so the id is stable across re-generations
  // of the same period. All callers converge on one id.
  const id = createHash("sha256")
    .update(`${opts.tenantId}:${opts.periodStart}:${opts.periodEnd}`)
    .digest("hex")
    .slice(0, 8) +
    "-" +
    createHash("sha256")
      .update(`${opts.tenantId}:${opts.periodStart}:${opts.periodEnd}`)
      .digest("hex")
      .slice(12, 16);

  // Sign the PDF before persisting — HMAC-SHA256 trailer proves the file
  // was generated by this daemon and hasn't been tampered with since.
  // keyDir default: ./data/keys (relative to cwd when opts.keyDir absent).
  const keyDir = opts.keyDir ?? join("data", KEY_DIR);
  const { pdfBytes: signedBytes, pdfHash, hmac, signedAt } = signPdf(
    Buffer.from(rendered.bytes),
    id,
    keyDir,
    () => new Date(now),
  );
  const pdfBase64 = Buffer.from(signedBytes).toString("base64");
  const pdfByteLength = signedBytes.byteLength;

  const db = getDb();
  const summaryJson = JSON.stringify(data);

  // Atomic upsert: inserts if no conflict on (tenant_id, period_start, period_end),
  // otherwise updates the existing row. The UNIQUE constraint in 0008_evidence_reports.ts
  // guarantees only one concurrent insert can succeed — all others get the conflict path.
  // @ts-ignore drizzle 0.38 single-default-enum inference quirk
  db.insert(evidenceReports)
    .values({
      id,
      tenantId: opts.tenantId,
      reportId: data.reportId,
      periodStart: opts.periodStart,
      periodEnd: opts.periodEnd,
      generatedAt: data.generatedAt,
      engineName: opts.engine.name,
      htmlSize: html.length,
      pdfByteLength: signedBytes.byteLength,
      pdfBase64,
      summaryJson,
      status: "complete",
      error: null,
      pdfHash,
      hmac,
      signedAt,
      createdAt: now,
      updatedAt: now,
    })
    .onConflictDoUpdate({
      target: [
        evidenceReports.tenantId,
        evidenceReports.periodStart,
        evidenceReports.periodEnd,
      ],
      set: {
        reportId: data.reportId,
        generatedAt: data.generatedAt,
        engineName: opts.engine.name,
        htmlSize: html.length,
        pdfByteLength: signedBytes.byteLength,
        pdfBase64,
        summaryJson,
        status: "complete",
        error: null,
        pdfHash,
        hmac,
        signedAt,
        updatedAt: now,
        // createdAt intentionally omitted — preserved from the original insert
      },
    })
    .run();

  return {
    id,
    reportId: data.reportId,
    tenantId: opts.tenantId,
    periodStart: opts.periodStart,
    periodEnd: opts.periodEnd,
    generatedAt: data.generatedAt,
    engineName: opts.engine.name,
    pdfByteLength,
    pdfBase64,
    htmlSize: html.length,
    status: "complete",
    summary: data,
    pdfHash,
    hmac,
    signedAt,
  };
}

interface AggregateInput {
  tenantId: string;
  periodStart: string;
  periodEnd: string;
  generatedAt: string;
}

export function aggregateEvidenceReportData(
  input: AggregateInput,
): EvidenceReportData {
  const db = getDb();
  const decisionRange = and(
    eq(policyDecisions.tenantId, input.tenantId),
    gte(policyDecisions.createdAt, input.periodStart),
    lt(policyDecisions.createdAt, input.periodEnd),
  );

  const total =
    db
      .select({ count: sql<number>`count(*)` })
      .from(policyDecisions)
      .where(decisionRange)
      .get()?.count ?? 0;
  const allowed =
    db
      .select({ count: sql<number>`count(*)` })
      .from(policyDecisions)
      .where(and(decisionRange, eq(policyDecisions.decision, "allow")))
      .get()?.count ?? 0;
  const blocked =
    db
      .select({ count: sql<number>`count(*)` })
      .from(policyDecisions)
      .where(and(decisionRange, eq(policyDecisions.decision, "block")))
      .get()?.count ?? 0;
  const reviewed =
    db
      .select({ count: sql<number>`count(*)` })
      .from(policyDecisions)
      .where(
        and(decisionRange, eq(policyDecisions.decision, "route_to_review")),
      )
      .get()?.count ?? 0;

  const summary: DecisionSummary = {
    totalDecisions: total,
    allowed,
    blocked,
    reviewed,
  };

  // Violations grouped by rule pack — only block + route_to_review count.
  const violationRows = db
    .select({
      rulePackId: policyDecisions.rulePackId,
      decision: policyDecisions.decision,
      count: sql<number>`count(*)`,
    })
    .from(policyDecisions)
    .where(decisionRange)
    .groupBy(policyDecisions.rulePackId, policyDecisions.decision)
    .all();

  const violationByPack = new Map<string, number>();
  for (const row of violationRows) {
    if (row.decision === "allow") continue;
    if (!row.rulePackId) continue;
    violationByPack.set(
      row.rulePackId,
      (violationByPack.get(row.rulePackId) ?? 0) + row.count,
    );
  }
  const violations: ViolationCategory[] = [...violationByPack.entries()].map(
    ([packId, count]) => ({
      rulePackId: packId,
      label: humanizeRulePack(packId),
      count,
    }),
  );

  // Findings — severity buckets + top-N highlights ordered by severity then
  // recency.
  const findingRange = and(
    eq(scannerFindings.tenantId, input.tenantId),
    gte(scannerFindings.createdAt, input.periodStart),
    lt(scannerFindings.createdAt, input.periodEnd),
  );

  const sevRows = db
    .select({
      severity: scannerFindings.severity,
      count: sql<number>`count(*)`,
    })
    .from(scannerFindings)
    .where(findingRange)
    .groupBy(scannerFindings.severity)
    .all();
  const findingsBySeverity: FindingsCategory[] = sevRows.map((r) => ({
    severity: r.severity,
    count: r.count,
  }));

  const highlightRows = db
    .select()
    .from(scannerFindings)
    .where(findingRange)
    .orderBy(desc(scannerFindings.createdAt))
    .limit(10)
    .all();
  const findingsHighlights: FindingHighlight[] = highlightRows.map((r) => ({
    id: r.id,
    severity: r.severity,
    title: r.title,
    affectedEndpoint: r.affectedEndpoint,
    status: r.status,
    ruleId: r.ruleId,
  }));

  const tenantRow = db
    .select({ name: tenants.name })
    .from(tenants)
    .where(eq(tenants.id, input.tenantId))
    .get();

  return {
    reportId: `er-${input.tenantId.slice(0, 8)}-${input.periodStart.slice(0, 7)}`,
    tenantId: input.tenantId,
    ...(tenantRow?.name ? { tenantLabel: tenantRow.name } : {}),
    periodStart: input.periodStart,
    periodEnd: input.periodEnd,
    generatedAt: input.generatedAt,
    summary,
    violations,
    findingsBySeverity,
    findingsHighlights,
  };
}

const RULE_PACK_LABELS: Record<string, string> = {
  "smb-starter": "SMB Baseline",
  "tcpa-real-estate": "TCPA — Real Estate",
  "fair-housing": "Fair Housing",
  // Match the YAML pack_id (rule-packs/hipaa-placeholder/*.yaml declares
  // pack_id: hipaa-healthcare). The directory name is legacy "placeholder"
  // and is not what the loader keys on.
  "hipaa-healthcare": "HIPAA — Healthcare",
};

function humanizeRulePack(packId: string): string {
  return RULE_PACK_LABELS[packId] ?? packId;
}
