/**
 * Evidence-report routes — PDF generation + persisted report listing.
 *
 *   POST /api/evidence-reports/generate
 *     Body:    { tenantId, periodStart, periodEnd }
 *     Returns: GenerateResult (includes pdfBase64 of the signed PDF)
 *
 *   GET  /api/evidence-reports
 *     Query:   tenantId, periodStart?, periodEnd?, limit?, offset?
 *     Returns: paginated list of evidence report metadata rows
 *
 * The PDF is generated by the PdfEngine configured in the daemon (Puppeteer in
 * production, FakePdfEngine in dev/test). All reports are HMAC-signed before
 * storage using keys stored in data/keys/ relative to the daemon's cwd.
 */

import { Router } from "express";
import { z } from "zod";
import { eq, desc } from "drizzle-orm";
import { getDb } from "../db/index.js";
import { evidenceReports } from "../db/schema.js";
import {
  generateEvidenceReport,
  type GenerateOptions,
} from "../services/evidence-report.js";
import type { Config } from "../config.js";
import type { PdfEngine } from "@agentworks/pdf";

const GenerateSchema = z.object({
  tenantId: z.string().uuid(),
  periodStart: z.string().datetime(),
  periodEnd: z.string().datetime(),
});

const ListSchema = z.object({
  tenantId: z.string().uuid(),
  periodStart: z.string().datetime().optional(),
  periodEnd: z.string().datetime().optional(),
  limit: z.coerce.number().int().min(1).max(100).default(20),
  offset: z.coerce.number().int().min(0).default(0),
});

/** Returns the PdfEngine from daemon config, throwing if not initialised. */
function requirePdfEngine(config: Config): PdfEngine {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const engine = (config as any).pdfEngine;
  if (!engine) {
    throw new Error(
      "PdfEngine not configured on this daemon. Set pdfEngine in daemon config or DAEMON_PDF_ENGINE env var.",
    );
  }
  return engine;
}

export function createEvidenceReportsRouter(config: Config): Router {
  const router = Router();

  // POST /api/evidence-reports/generate
  router.post("/generate", (req, res) => {
    const parsed = GenerateSchema.safeParse(req.body);
    if (!parsed.success) {
      res
        .status(400)
        .json({ error: "invalid_request", details: parsed.error.flatten() });
      return;
    }

    const { tenantId, periodStart, periodEnd } = parsed.data;
    if (periodStart >= periodEnd) {
      res.status(400).json({
        error: "invalid_period",
        message: "periodStart must be before periodEnd",
      });
      return;
    }

    let engine: PdfEngine;
    try {
      engine = requirePdfEngine(config);
    } catch (err) {
      res.status(500).json({ error: "pdf_engine_unavailable", message: (err as Error).message });
      return;
    }

    const opts: GenerateOptions = {
      tenantId,
      periodStart,
      periodEnd,
      engine,
    };

    generateEvidenceReport(opts)
      .then((result) => {
        res.status(200).json(result);
      })
      .catch((err: unknown) => {
        console.error("generateEvidenceReport failed:", err);
        res.status(500).json({
          error: "generation_failed",
          message: (err as Error).message,
        });
      });
  });

  // GET /api/evidence-reports
  router.get("/", (req, res) => {
    const parsed = ListSchema.safeParse(req.query);
    if (!parsed.success) {
      res
        .status(400)
        .json({ error: "invalid_request", details: parsed.error.flatten() });
      return;
    }

    const { tenantId, periodStart, periodEnd, limit, offset } = parsed.data;
    const db = getDb();

    const rows = db
      .select({
        id: evidenceReports.id,
        reportId: evidenceReports.reportId,
        tenantId: evidenceReports.tenantId,
        periodStart: evidenceReports.periodStart,
        periodEnd: evidenceReports.periodEnd,
        generatedAt: evidenceReports.generatedAt,
        engineName: evidenceReports.engineName,
        pdfByteLength: evidenceReports.pdfByteLength,
        status: evidenceReports.status,
        pdfHash: evidenceReports.pdfHash,
        hmac: evidenceReports.hmac,
        signedAt: evidenceReports.signedAt,
      })
      .from(evidenceReports)
      .where(eq(evidenceReports.tenantId, tenantId))
      .orderBy(desc(evidenceReports.generatedAt))
      .limit(limit)
      .offset(offset)
      .all();

    const countRow = db
      .select({ count: evidenceReports.id })
      .from(evidenceReports)
      .where(eq(evidenceReports.tenantId, tenantId))
      .get();

    res.json({
      data: rows,
      pagination: {
        total: countRow?.count ?? rows.length,
        limit,
        offset,
      },
    });
  });

  return router;
}
